server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: news
          uri: http://news.baidu.com/internet
          predicates:
            - Path=/internet