spring:
  application:
    name: gateway
  redis:
    host: 192.168.133.130
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: news
          uri: http://news.baidu.com/internet
          predicates:
            - Path=/internet

server.port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:pwd@peer1:9001/eureka,http://user:pwd@peer2:9002/eureka,http://user:pwd@peer3:9003/eureka